// @flow

/**
 * All redux actions are events
 */

export default {
  CART_CHECKOUT_REQUESTED: 'CART_CHECKOUT_REQUESTED',
  CART_ITEM_TOGGLED: 'CART_ITEM_TOGGLED',
  SEARCHTEXT_CHANGED: 'SEARCHTEXT_CHANGED',
  ITEMS_LOADED: 'ITEMS_LOADED',
  ITEMS_LOADING_FAILED: 'ITEMS_LOADING_FAILED'
};
